name: Deploy AWS Lambda

on: # when we trigger a PUSH in MAIN branch in the LAMBDA folder it will trigger the JOB mentioned below in the code
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

      # below code is for the conditions met for the above mentioned logic
jobs:
  deploy-lambda: #name of our JOB
    runs-on: ubuntu-latest #sets or specifies the runner machine
    steps: 
      - uses: actions/checkout@v2

      - name: Set up python # sets up python ENV
        uses: actions/setup-python@v2
        with: 
          python-version: '3.12'

      - name: Install Dependencies # this install any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Creds # this sets up our AWS creds
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.FJ89_AWS_PUB_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FJ89_AWS_PRIV_ACCESS_KEY_ID }}
          aws-region: ap-southeast-1  
            
      - name: Deploy Lambda Function # zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip      